// Created an event listener for numeric and operator keypresses
document.addEventListener("keypress", function(event) {
    if (/[0-9+\-*/.]/.test(event.key)) {
      var numOps = document.getElementById("input");
      numOps.textContent += event.key;
      // "entry" will be used for the splitString function
      entry = numOps.textContent;
    }
  });

// Stores the operator as a variable
document.addEventListener("keypress", function(event) {
  if (/[+\-*/]/.test(event.key)) {
    // "operator" will be used for the splitString function
    operator = event.key;
  }
});

// Created an event listener for "enter" key, which will execute several activities
document.addEventListener("keypress", function(event) {
  if (event.key === 'Enter') {
    // numOps and output need to be called since they will be both be interacted with
    var numOps = document.getElementById("input");
    var output = document.getElementById("output");
    // when "enter" is pressed, the splitString function is called
    splitString(entry, operator);
    // Block calls the calculator function and write the output to #output; numOps.textContent is cleared
    output.textContent = calculator(calculation.num1, calculation.num2, calculation.delim);
    numOps.textContent = "";
  }
})

// This function will take the input and split it into two numbers, and a delimiter
function splitString(str, delimiter) {
  // Split the string into an array of numbers
  const nums = str.split(delimiter).map(Number);
  const [num1, num2] = nums;
  const delim = delimiter;

  // stores variables as an object and returns the object
  calculation = { num1, num2, delim };
  return calculation;
}

// Takes values generated by splitString function and runs operations. Returns "Error" when operations incorrectly used
function calculator (a, b, operation) {
  if (a != a || b != b) {
    return "ERROR";
  } else if (operation === "+") {
    return a + b;
  } else if (operation === "-") {
    return a - b;
  } else if (operation === "*") {
    return a * b;
  } else if (operation === "/") {
    return a / b;
  } else {
    return "ERROR"
  }
}
